<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE group [
        <!ELEMENT group (student*)>
        <!ELEMENT student (subject*,average?)>
        <!ATTLIST student
                firstname CDATA #REQUIRED
                lastname CDATA #REQUIRED
                groupnumber CDATA #REQUIRED>
        <!ELEMENT subject EMPTY>
        <!ATTLIST subject
                title CDATA #REQUIRED
                mark (1|2|3|4|5) #REQUIRED>
        <!ELEMENT average (#PCDATA)>
        ]>

<group>
    <student firstname="Valeriy" lastname="Zhmishenko" groupnumber="2">
        <subject title="Maths" mark="5"/>
        <subject title="Chemistry" mark="5"/>
        <subject title="History" mark="3"/>
        <subject title="Physics" mark="5"/>
        <subject title="Spanish" mark="3"/>
        <average>4.0</average>
    </student>

    <student firstname="Denis" lastname="Petrov" groupnumber="8">
        <subject title="Maths" mark="4"/>
        <subject title="Chemistry" mark="2"/>
        <subject title="History" mark="2"/>
        <subject title="Physics" mark="3"/>
        <subject title="Spanish" mark="2"/>
        <average>4.0</average>
    </student>
</group>